from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime
import os

def generate_report(evaluations, output_path, title="RustVision Inspection Report"):
    """Generate beautiful industry-standard PDF report for corrosion detection"""
    
    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    # Create document
    doc = SimpleDocTemplate(output_path, pagesize=A4,
                          rightMargin=2*cm, leftMargin=2*cm,
                          topMargin=2.5*cm, bottomMargin=2*cm)
    
    # Container for the 'Flowable' objects
    elements = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=28,
        textColor=colors.HexColor('#8B4513'),
        spaceAfter=35,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold',
        leading=32
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#A85D3A'),
        spaceAfter=14,
        fontName='Helvetica-Bold',
        leading=20
    )
    
    header_style = ParagraphStyle(
        'Header',
        parent=styles['Normal'],
        fontSize=11,
        textColor=colors.HexColor('#666666'),
        alignment=TA_RIGHT,
        fontName='Helvetica-Bold'
    )
    
    normal_style = ParagraphStyle(
        'NormalStyle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.black,
        leading=14,
        spaceAfter=12
    )
    
    # ===== COVER PAGE =====
    # Company Header
    elements.append(Paragraph(
        "RUSTVISION<br/>AI-Powered Corrosion Detection System",
        header_style
    ))
    elements.append(Spacer(1, 2.5*cm))
    
    # Title
    elements.append(Paragraph(title, title_style))
    elements.append(Spacer(1, 2*cm))
    
    # Report Metadata Table
    report_date = datetime.now().strftime('%B %d, %Y')
    report_time = datetime.now().strftime('%I:%M %p')
    
    metadata_data = [
        ['Report Type:', 'Automated Corrosion Inspection'],
        ['Inspection Date:', report_date],
        ['Inspection Time:', report_time],
        ['Total Evaluations:', str(len(evaluations))],
        ['System:', 'RustVision AI (YOLOv11)'],
        ['Generated By:', 'Automated Detection System'],
    ]
    
    metadata_table = Table(metadata_data, colWidths=[5*cm, 8*cm])
    metadata_table.setStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F5F1EB')),
        ('BACKGROUND', (1, 0), (1, -1), colors.white),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (0, -1), 'LEFT'),
        ('ALIGN', (1, 0), (1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#E5DDD3')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ])
    elements.append(metadata_table)
    elements.append(PageBreak())
    
    # ===== EXECUTIVE SUMMARY =====
    elements.append(Paragraph("Executive Summary", heading_style))
    
    total_detections = len(evaluations)
    avg_confidence = sum(e.get("confidence", 0) for e in evaluations) / total_detections if evaluations else 0
    
    summary_text = f"""This report presents the results of automated corrosion detection analysis performed using RustVision AI system. The inspection identified {total_detections} corrosion detection{'s' if total_detections != 1 else ''} with an average confidence level of {avg_confidence:.1%}.
    
Each detection has been visually annotated and documented in the following sections. The system uses advanced computer vision algorithms to identify surface degradation and corrosion patterns in industrial infrastructure."""
    
    elements.append(Paragraph(summary_text, normal_style))
    elements.append(Spacer(1, 0.5*cm))

    # Summary Table of All Inspections
    summary_data = [['ID', 'Inspection Image', 'Confidence', 'Risk Level']]
    
    for idx, eval_data in enumerate(evaluations, start=1):
        conf = eval_data.get("confidence", 0)
        risk = "High" if conf > 0.85 else "Medium" if conf > 0.70 else "Low"
        
        # Get filename relative to media root or just basename for display
        img_name = os.path.basename(eval_data.get("original", f"Image {idx}"))
        # Truncate if too long
        if len(img_name) > 25:
            img_name = img_name[:22] + "..."
            
        summary_data.append([
            str(idx),
            img_name,
            f"{conf:.1%}",
            risk
        ])

    summary_table = Table(summary_data, colWidths=[1.5*cm, 8.5*cm, 3*cm, 3*cm])
    summary_table.setStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#E8C4A0')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#8B4513')),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('TOPPADDING', (0, 0), (-1, 0), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#C97D60')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#FAF8F5')]),
    ])
    elements.append(summary_table)
    elements.append(Spacer(1, 0.8*cm))
    
    # ===== DETAILED EVALUATIONS =====
    elements.append(Paragraph("Detailed Inspection Results", heading_style))
    elements.append(Spacer(1, 0.5*cm))
    
    for idx, eval_data in enumerate(evaluations, start=1):
        # Evaluation Header
        elements.append(Paragraph(
            f"Inspection #{idx}",
            ParagraphStyle(
                'EvalHeader',
                parent=styles['Heading3'],
                fontSize=13,
                textColor=colors.HexColor('#C97D60'),
                spaceAfter=10,
                fontName='Helvetica-Bold'
            )
        ))
        
        # Images Table
        try:
            original_img = Image(eval_data["original"], width=7.5*cm, height=5.5*cm)
            detected_img = Image(eval_data["detected"], width=7.5*cm, height=5.5*cm)
            
            img_table = Table([
                ['Original Image', 'Detected Corrosion'],
                [original_img, detected_img]
            ], colWidths=[7.5*cm, 7.5*cm])
            
            img_table.setStyle([
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 11),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#8B4513')),
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#E8C4A0')),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
                ('TOPPADDING', (0, 0), (-1, 0), 8),
                ('GRID', (0, 0), (-1, -1), 1.5, colors.HexColor('#C97D60')),
                ('BOTTOMPADDING', (0, 1), (-1, 1), 8),
                ('TOPPADDING', (0, 1), (-1, 1), 8),
            ])
            elements.append(img_table)
        except Exception as e:
            elements.append(Paragraph(f"Images could not be loaded: {str(e)}", normal_style))
        
        elements.append(Spacer(1, 0.5*cm))
        
        # Detection Details Table
        confidence = eval_data.get("confidence", 0)
        severity = "High" if confidence > 0.85 else "Medium" if confidence > 0.70 else "Low"
        severity_color = colors.HexColor('#C0392B') if severity == "High" else colors.HexColor('#F39C12') if severity == "Medium" else colors.HexColor('#27AE60')
        
        details_data = [
            ['Detection Class:', 'Corrosion/Rust'],
            ['Confidence Level:', f'{confidence:.1%}'],
            ['Severity Rating:', severity],
            ['Status:', 'Requires Review'],
        ]
        
        details_table = Table(details_data, colWidths=[4.5*cm, 10.5*cm])
        details_table.setStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#FAF8F5')),
            ('BACKGROUND', (1, 0), (1, -1), colors.white),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('TEXTCOLOR', (1, 2), (1, 2), severity_color),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.8, colors.HexColor('#E5DDD3')),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ])
        elements.append(details_table)
        
        # Add page break between evaluations (except last)
        if idx < len(evaluations):
            elements.append(PageBreak())
        else:
            elements.append(Spacer(1, 1.2*cm))
    
    # ===== FOOTER NOTES =====
    elements.append(Spacer(1, 0.8*cm))
    notes_style = ParagraphStyle(
        'Notes',
        parent=normal_style,
        fontSize=9,
        textColor=colors.HexColor('#666666'),
        leftIndent=0.5*cm,
        spaceBefore=8,
        bulletIndent=0.5*cm,
        bulletFontName='Helvetica-Bold'
    )
    
    notes_text = """Notes:
• This report is generated automatically by RustVision AI system
• All detections should be verified by qualified inspection personnel
• Confidence scores indicate the AI system's certainty in detection accuracy
• Recommended follow-up actions should be determined based on industry standards and regulations"""
    
    elements.append(Paragraph(notes_text, notes_style))
    
    # ===== FOOTER =====
    elements.append(Spacer(1, 1.2*cm))
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#999999'),
        alignment=TA_CENTER,
        fontName='Helvetica-Oblique'
    )
    footer_text = f"Report generated on {report_date} at {report_time}<br/>RustVision AI System - Automated Industrial Inspection"
    elements.append(Paragraph(footer_text, footer_style))
    
    # Build PDF
    doc.build(elements)
